"""new versions123

Revision ID: 09f966ae154c
Revises: af36c33fe5d8
Create Date: 2026-04-08 17:27:55.097134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09f966ae154c'
down_revision: Union[str, Sequence[str], None] = 'af36c33fe5d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Удаляем дубликаты перед созданием UNIQUE constraint
    op.execute("""
        DELETE FROM agsk 
        WHERE id IN (
            SELECT id 
            FROM (
                SELECT id, ROW_NUMBER() OVER (PARTITION BY code ORDER BY id) as row_num 
                FROM agsk 
                WHERE code IS NOT NULL
            ) t 
            WHERE row_num > 1
        );
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'agsk', ['code'])
    op.create_foreign_key(None, 'plan_item_versions', 'agsk', ['agsk_id'], ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plan_item_versions', type_='foreignkey')
    op.drop_constraint(None, 'agsk', type_='unique')
    # ### end Alembic commands ###
