"""Add executed_amount to PlanItemVersion

Revision ID: 0a18404896d2
Revises: c145b43dde34
Create Date: 2025-12-31 12:26:57.398403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a18404896d2'
down_revision: Union[str, Sequence[str], None] = 'c145b43dde34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan_item_versions', sa.Column('executed_amount', sa.Numeric(precision=18, scale=2), nullable=False))
    op.alter_column('plan_item_versions', 'executed_quantity',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plan_item_versions', 'executed_quantity',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=True)
    op.drop_column('plan_item_versions', 'executed_amount')
    # ### end Alembic commands ###
