"""Add additional_specs to PlanItemVersion

Revision ID: 0a82f9e0fa8a
Revises: a564a7fe9e75
Create Date: 2026-01-12 10:17:42.578209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a82f9e0fa8a'
down_revision: Union[str, Sequence[str], None] = 'a564a7fe9e75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan_item_versions', sa.Column('additional_specs', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan_item_versions', 'additional_specs')
    # ### end Alembic commands ###
