"""remove_additional_specs_kz

Revision ID: 0e3188729ab3
Revises: ee71551c0db6
Create Date: 2026-04-30 11:18:27.940022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e3188729ab3'
down_revision: Union[str, Sequence[str], None] = 'ee71551c0db6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan_item_versions', 'additional_specs_kz')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan_item_versions', sa.Column('additional_specs_kz', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
