"""delete residency executions

Revision ID: 0f85a22ac939
Revises: 2ea622efb78e
Create Date: 2026-01-30 09:48:25.798834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f85a22ac939'
down_revision: Union[str, Sequence[str], None] = '2ea622efb78e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan_item_executions', sa.Column('fact_vc_percentage', sa.Numeric(precision=5, scale=2), nullable=True))
    op.drop_column('plan_item_executions', 'origin_code')
    op.drop_column('plan_item_executions', 'residency_code')
    op.add_column('procurement_plan_versions', sa.Column('executed_vc_amount', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('procurement_plan_versions', sa.Column('executed_vc_percentage', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('procurement_plan_versions', 'executed_vc_percentage')
    op.drop_column('procurement_plan_versions', 'executed_vc_amount')
    op.add_column('plan_item_executions', sa.Column('residency_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('plan_item_executions', sa.Column('origin_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('plan_item_executions', 'fact_vc_percentage')
    # ### end Alembic commands ###
