"""new versiooon7

Revision ID: 130e7b4f1e54
Revises: ce0ca072ee48
Create Date: 2026-02-06 09:34:12.593064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '130e7b4f1e54'
down_revision: Union[str, Sequence[str], None] = 'ce0ca072ee48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_reestr_ktp_agsk3_code'), 'reestr_ktp', ['agsk3_code'], unique=False)
    op.create_index(op.f('ix_reestr_ktp_enstru_code'), 'reestr_ktp', ['enstru_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reestr_ktp_enstru_code'), table_name='reestr_ktp')
    op.drop_index(op.f('ix_reestr_ktp_agsk3_code'), table_name='reestr_ktp')
    # ### end Alembic commands ###
