"""remove_enstru_from_agsk_matches

Revision ID: 1db0735cc7fc
Revises: 5669086d393a
Create Date: 2026-04-29 16:22:28.116266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1db0735cc7fc'
down_revision: Union[str, Sequence[str], None] = '5669086d393a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('agsk_reestr_ktp_matches_enstru_code_fkey', 'agsk_reestr_ktp_matches', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('agsk_reestr_ktp_matches_enstru_code_fkey', 'agsk_reestr_ktp_matches', 'enstru', ['enstru_code'], ['code'])
    # ### end Alembic commands ###
