"""delete vc_median

Revision ID: 2ea622efb78e
Revises: 4e4ab418e4c8
Create Date: 2026-01-27 16:41:53.085636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ea622efb78e'
down_revision: Union[str, Sequence[str], None] = '4e4ab418e4c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('procurement_plan_versions', sa.Column('vc_percentage', sa.Numeric(precision=5, scale=2), nullable=True))
    op.drop_column('procurement_plan_versions', 'vc_mean')
    op.drop_column('procurement_plan_versions', 'vc_median')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('procurement_plan_versions', sa.Column('vc_median', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('procurement_plan_versions', sa.Column('vc_mean', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.drop_column('procurement_plan_versions', 'vc_percentage')
    # ### end Alembic commands ###
