"""new versiooon10

Revision ID: 3b2e718abfa7
Revises: 3bbc9ad53f04
Create Date: 2026-03-25 22:58:34.877463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b2e718abfa7'
down_revision: Union[str, Sequence[str], None] = '3bbc9ad53f04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_agsk_matches_agsk', table_name='enstru_agsk_matches_v2')
    op.drop_index('idx_agsk_matches_enstru', table_name='enstru_agsk_matches_v2')
    op.drop_index('idx_agsk_matches_score', table_name='enstru_agsk_matches_v2')
    op.drop_table('enstru_agsk_matches_v2')
    op.drop_index('idx_excl_score', table_name='agsk_enstru_exclusive')
    op.drop_table('agsk_enstru_exclusive')
    op.drop_index('idx_matches_enstru', table_name='enstru_agsk_matches')
    op.drop_index('idx_matches_score', table_name='enstru_agsk_matches')
    op.drop_table('enstru_agsk_matches')
    op.drop_index('idx_agsk_name_trgm', table_name='agsk', postgresql_using='gin')
    op.drop_index('idx_agsk_search_trgm', table_name='agsk', postgresql_using='gin')
    op.drop_column('agsk', 'search_text')
    op.drop_index('idx_enstru_name_trgm', table_name='enstru', postgresql_using='gin')
    op.drop_index('idx_enstru_search_trgm', table_name='enstru', postgresql_using='gin')
    op.drop_column('enstru', 'search_text')
    op.create_index('idx_reestr_ktp_enstru_codes', 'reestr_ktp', ['enstru_codes'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_reestr_ktp_enstru_codes', table_name='reestr_ktp', postgresql_using='gin')
    op.add_column('enstru', sa.Column('search_text', sa.TEXT(), sa.Computed("lower(((((COALESCE(name_rus, ''::text) || ' '::text) || COALESCE(detail_rus, ''::text)) || ' '::text) || COALESCE(standard, ''::text)))", persisted=True), autoincrement=False, nullable=True))
    op.create_index('idx_enstru_search_trgm', 'enstru', ['search_text'], unique=False, postgresql_using='gin')
    op.create_index('idx_enstru_name_trgm', 'enstru', [sa.text("lower(COALESCE(name_rus, ''::text))")], unique=False, postgresql_using='gin')
    op.add_column('agsk', sa.Column('search_text', sa.TEXT(), sa.Computed("lower(((((COALESCE(name_ru, ''::text) || ' '::text) || COALESCE(full_name, ''::text)) || ' '::text) || COALESCE(standart, ''::text)))", persisted=True), autoincrement=False, nullable=True))
    op.create_index('idx_agsk_search_trgm', 'agsk', ['search_text'], unique=False, postgresql_using='gin')
    op.create_index('idx_agsk_name_trgm', 'agsk', [sa.text("lower(COALESCE(name_ru, ''::text))")], unique=False, postgresql_using='gin')
    op.create_table('enstru_agsk_matches',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('enstru_code', sa.VARCHAR(length=35), autoincrement=False, nullable=True),
    sa.Column('agsk_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name_ru_enstru', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name_ru_agsk', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('agsk_full_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('detail_enstru', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('standard_enstru', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='enstru_agsk_matches_pkey')
    )
    op.create_index('idx_matches_score', 'enstru_agsk_matches', [sa.text('score DESC')], unique=False)
    op.create_index('idx_matches_enstru', 'enstru_agsk_matches', ['enstru_code'], unique=False)
    op.create_table('agsk_enstru_exclusive',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('agsk_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('enstru_code', sa.VARCHAR(length=35), autoincrement=False, nullable=True),
    sa.Column('name_ru_agsk', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('agsk_full_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name_ru_enstru', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('detail_enstru', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('standard_enstru', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='agsk_enstru_exclusive_pkey'),
    sa.UniqueConstraint('agsk_code', name='agsk_enstru_exclusive_agsk_code_key'),
    sa.UniqueConstraint('enstru_code', name='agsk_enstru_exclusive_enstru_code_key')
    )
    op.create_index('idx_excl_score', 'agsk_enstru_exclusive', [sa.text('score DESC')], unique=False)
    op.create_table('enstru_agsk_matches_v2',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('agsk_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('enstru_code', sa.VARCHAR(length=35), autoincrement=False, nullable=True),
    sa.Column('name_ru_agsk', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('agsk_full_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name_ru_enstru', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('detail_enstru', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('standard_enstru', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='enstru_agsk_matches_v2_pkey')
    )
    op.create_index('idx_agsk_matches_score', 'enstru_agsk_matches_v2', [sa.text('score DESC')], unique=False)
    op.create_index('idx_agsk_matches_enstru', 'enstru_agsk_matches_v2', ['enstru_code'], unique=False)
    op.create_index('idx_agsk_matches_agsk', 'enstru_agsk_matches_v2', ['agsk_code'], unique=False)
    # ### end Alembic commands ###
