"""new versiooon9

Revision ID: 3bbc9ad53f04
Revises: eeefdd934411
Create Date: 2026-03-16 10:10:40.022909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3bbc9ad53f04'
down_revision: Union[str, Sequence[str], None] = 'eeefdd934411'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agsk2')
    op.add_column('agsk', sa.Column('full_name', sa.Text(), nullable=True))
    op.alter_column('agsk', 'group',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('agsk', 'code',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               nullable=True)
    op.alter_column('agsk', 'name_ru',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('reestr_ktp', sa.Column('tnved_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('reestr_ktp', sa.Column('kpved_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('reestr_ktp', sa.Column('kpved_names', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('reestr_ktp', sa.Column('enstru_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('reestr_ktp', sa.Column('enstru_names', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('reestr_ktp', sa.Column('agsk3_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('reestr_ktp', sa.Column('agsk3_names', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('reestr_ktp', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('reestr_ktp', sa.Column('hidden_at', sa.DateTime(), nullable=True))
    op.add_column('reestr_ktp', sa.Column('hidden_reason', sa.Text(), nullable=True))
    op.add_column('reestr_ktp', sa.Column('data_source', sa.Text(), nullable=True))
    op.alter_column('reestr_ktp', 'product_code',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('reestr_ktp', 'registration_number',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('reestr_ktp', 'bin_iin',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.Text(),
               nullable=True)
    op.alter_column('reestr_ktp', 'company_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               nullable=True)

    # FIX: Add postgresql_using for JSONB conversion (setting to NULL to avoid errors)
    op.alter_column('reestr_ktp', 'oked_codes',
               existing_type=sa.VARCHAR(length=50),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using='NULL')

    op.alter_column('reestr_ktp', 'oked_names',
               existing_type=sa.TEXT(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using='NULL')

    op.alter_column('reestr_ktp', 'region_kato',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('reestr_ktp', 'website',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('reestr_ktp', 'phone',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('reestr_ktp', 'email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('reestr_ktp', 'product_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('reestr_ktp', 'production_capacity',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('reestr_ktp', 'dvc_percent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('reestr_ktp', 'localization_level',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('reestr_ktp', 'registry_inclusion_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True,
               postgresql_using='registry_inclusion_date::timestamp') # Cast date to timestamp

    op.drop_index('ix_reestr_ktp_agsk3_code', table_name='reestr_ktp')
    op.drop_index('ix_reestr_ktp_bin_iin', table_name='reestr_ktp')
    op.drop_index('ix_reestr_ktp_enstru_code', table_name='reestr_ktp')
    op.drop_column('reestr_ktp', 'tnved_code_10')
    op.drop_column('reestr_ktp', 'kpved_code')
    op.drop_column('reestr_ktp', 'kpved_name')
    op.drop_column('reestr_ktp', 'agsk3_code')
    op.drop_column('reestr_ktp', 'agsk3_name')
    op.drop_column('reestr_ktp', 'enstru_name')
    op.drop_column('reestr_ktp', 'enstru_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reestr_ktp', sa.Column('enstru_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('reestr_ktp', sa.Column('enstru_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('reestr_ktp', sa.Column('agsk3_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('reestr_ktp', sa.Column('agsk3_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('reestr_ktp', sa.Column('kpved_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('reestr_ktp', sa.Column('kpved_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('reestr_ktp', sa.Column('tnved_code_10', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.create_index('ix_reestr_ktp_enstru_code', 'reestr_ktp', ['enstru_code'], unique=False)
    op.create_index('ix_reestr_ktp_bin_iin', 'reestr_ktp', ['bin_iin'], unique=False)
    op.create_index('ix_reestr_ktp_agsk3_code', 'reestr_ktp', ['agsk3_code'], unique=False)
    op.alter_column('reestr_ktp', 'registry_inclusion_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('reestr_ktp', 'localization_level',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('reestr_ktp', 'dvc_percent',
               existing_type=sa.Text(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('reestr_ktp', 'production_capacity',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('reestr_ktp', 'product_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('reestr_ktp', 'email',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('reestr_ktp', 'phone',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('reestr_ktp', 'website',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('reestr_ktp', 'region_kato',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('reestr_ktp', 'oked_names',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True,
               postgresql_using='NULL')
    op.alter_column('reestr_ktp', 'oked_codes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               postgresql_using='NULL')
    op.alter_column('reestr_ktp', 'company_name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('reestr_ktp', 'bin_iin',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=12),
               nullable=False)
    op.alter_column('reestr_ktp', 'registration_number',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('reestr_ktp', 'product_code',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('reestr_ktp', 'data_source')
    op.drop_column('reestr_ktp', 'hidden_reason')
    op.drop_column('reestr_ktp', 'hidden_at')
    op.drop_column('reestr_ktp', 'is_active')
    op.drop_column('reestr_ktp', 'agsk3_names')
    op.drop_column('reestr_ktp', 'agsk3_codes')
    op.drop_column('reestr_ktp', 'enstru_names')
    op.drop_column('reestr_ktp', 'enstru_codes')
    op.drop_column('reestr_ktp', 'kpved_names')
    op.drop_column('reestr_ktp', 'kpved_codes')
    op.drop_column('reestr_ktp', 'tnved_codes')
    op.alter_column('agsk', 'name_ru',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('agsk', 'code',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('agsk', 'group',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('agsk', 'full_name')
    op.create_table('agsk2',
    sa.Column('group', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('full_name_ru', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('standart', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('unit', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('parent_code', sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
