"""new versions14.04.2026

Revision ID: 46cf5b5c9193
Revises: 09f966ae154c
Create Date: 2026-04-14 15:51:46.659555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46cf5b5c9193'
down_revision: Union[str, Sequence[str], None] = '09f966ae154c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_documents', sa.Column('is_test', sa.Boolean(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('external_documents', 'is_test')
    # ### end Alembic commands ###
