"""delete ktp_percent

Revision ID: 4e4ab418e4c8
Revises: 7defd734427f
Create Date: 2026-01-27 16:13:38.996196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e4ab418e4c8'
down_revision: Union[str, Sequence[str], None] = '7defd734427f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('procurement_plan_versions', 'ktp_percentage')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('procurement_plan_versions', sa.Column('ktp_percentage', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
