"""add not ktp

Revision ID: 5669086d393a
Revises: f2065a160a9a
Create Date: 2026-04-29 14:31:16.220086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5669086d393a'
down_revision: Union[str, Sequence[str], None] = 'f2065a160a9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psd_document_items', sa.Column('not_in_ktp_registry', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('psd_document_items', 'not_in_ktp_registry')
    # ### end Alembic commands ###
