"""add assigned fields to external documents

Revision ID: 58596b0a8249
Revises: 60567698f645
Create Date: 2026-03-26 03:08:39.113146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58596b0a8249'
down_revision: Union[str, Sequence[str], None] = '60567698f645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_documents', sa.Column('assigned_to', sa.Integer(), nullable=True))
    op.add_column('external_documents', sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'external_documents', 'users', ['assigned_to'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'external_documents', type_='foreignkey')
    op.drop_column('external_documents', 'assigned_at')
    op.drop_column('external_documents', 'assigned_to')
    # ### end Alembic commands ###
