"""Initial migration for Postgres

Revision ID: 598e8d8a641c
Revises: 
Create Date: 2025-12-25 13:07:12.466302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '598e8d8a641c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agsk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group', sa.Text(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name_ru', sa.Text(), nullable=False),
    sa.Column('standart', sa.Text(), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('cost_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_ru', sa.Text(), nullable=False),
    sa.Column('name_kz', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enstru',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=35), nullable=False),
    sa.Column('name_ru', sa.Text(), nullable=False),
    sa.Column('name_kz', sa.Text(), nullable=False),
    sa.Column('type_ru', sa.Text(), nullable=False),
    sa.Column('type_kz', sa.Text(), nullable=False),
    sa.Column('specs_ru', sa.Text(), nullable=True),
    sa.Column('specs_kz', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('kato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name_kz', sa.Text(), nullable=False),
    sa.Column('name_ru', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('mkei',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name_kz', sa.Text(), nullable=False),
    sa.Column('name_ru', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('reestr_ktp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reg_number_application', sa.Integer(), nullable=True),
    sa.Column('bin_iin', sa.String(length=12), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('type_activity_oked', sa.String(length=30), nullable=False),
    sa.Column('kato_code', sa.String(length=30), nullable=False),
    sa.Column('actual_address', sa.Text(), nullable=True),
    sa.Column('product_name_ru', sa.Text(), nullable=True),
    sa.Column('product_name_kz', sa.Text(), nullable=True),
    sa.Column('unit_per_year', sa.String(length=20), nullable=False),
    sa.Column('tn_ved', sa.String(length=10), nullable=True),
    sa.Column('kpved', sa.String(length=20), nullable=True),
    sa.Column('ens_tru_code', sa.String(length=35), nullable=False),
    sa.Column('agsk_code', sa.String(length=50), nullable=True),
    sa.Column('level_localization', sa.Integer(), nullable=True),
    sa.Column('date_add_reestr', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_funding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_ru', sa.Text(), nullable=False),
    sa.Column('name_kz', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iin', sa.String(length=12), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('bin', sa.String(length=12), nullable=True),
    sa.Column('org_name', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_bin'), 'users', ['bin'], unique=False)
    op.create_index(op.f('ix_users_iin'), 'users', ['iin'], unique=True)
    op.create_table('procurement_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(length=128), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('procurement_plan_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PRE_APPROVED', 'APPROVED', name='planstatus'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('ktp_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('import_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['procurement_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'version_number', name='uq_plan_version')
    )
    op.create_table('plan_item_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('item_number', sa.Integer(), nullable=False),
    sa.Column('need_type', sa.Enum('GOODS', 'WORKS', 'SERVICES', name='needtype'), nullable=False),
    sa.Column('trucode', sa.String(length=35), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('expense_item_id', sa.Integer(), nullable=False),
    sa.Column('funding_source_id', sa.Integer(), nullable=False),
    sa.Column('agsk_id', sa.String(length=50), nullable=True),
    sa.Column('kato_purchase_id', sa.Integer(), nullable=True),
    sa.Column('kato_delivery_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('price_per_unit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('is_ktp', sa.Boolean(), nullable=True),
    sa.Column('is_resident', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('root_item_id', sa.Integer(), nullable=True),
    sa.Column('source_version_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['agsk_id'], ['agsk.code'], ),
    sa.ForeignKeyConstraint(['expense_item_id'], ['cost_items.id'], ),
    sa.ForeignKeyConstraint(['funding_source_id'], ['source_funding.id'], ),
    sa.ForeignKeyConstraint(['kato_delivery_id'], ['kato.id'], ),
    sa.ForeignKeyConstraint(['kato_purchase_id'], ['kato.id'], ),
    sa.ForeignKeyConstraint(['source_version_id'], ['procurement_plan_versions.id'], ),
    sa.ForeignKeyConstraint(['trucode'], ['enstru.code'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['mkei.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['procurement_plan_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'item_number', name='uq_version_item')
    )
    op.create_index(op.f('ix_plan_item_versions_root_item_id'), 'plan_item_versions', ['root_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plan_item_versions_root_item_id'), table_name='plan_item_versions')
    op.drop_table('plan_item_versions')
    op.drop_table('procurement_plan_versions')
    op.drop_table('procurement_plans')
    op.drop_index(op.f('ix_users_iin'), table_name='users')
    op.drop_index(op.f('ix_users_bin'), table_name='users')
    op.drop_table('users')
    op.drop_table('source_funding')
    op.drop_table('reestr_ktp')
    op.drop_table('mkei')
    op.drop_table('kato')
    op.drop_table('enstru')
    op.drop_table('cost_items')
    op.drop_table('agsk')
    # ### end Alembic commands ###
