"""add psd analyst tables

Revision ID: 60567698f645
Revises: 60af76a7b408
Create Date: 2026-03-26 03:00:59.237502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60567698f645'
down_revision: Union[str, Sequence[str], None] = '60af76a7b408'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_tasks', sa.Column('assigned_to', sa.Integer(), nullable=True))
    op.add_column('admin_tasks', sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'admin_tasks', 'users', ['assigned_to'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admin_tasks', type_='foreignkey')
    op.drop_column('admin_tasks', 'assigned_at')
    op.drop_column('admin_tasks', 'assigned_to')
    # ### end Alembic commands ###
