"""Add is_executed to ProcurementPlanVersion

Revision ID: 6082afeeb7f8
Revises: 598e8d8a641c
Create Date: 2025-12-25 16:32:36.890732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6082afeeb7f8'
down_revision: Union[str, Sequence[str], None] = '598e8d8a641c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('procurement_plan_versions', sa.Column('is_executed', sa.Boolean(), nullable=False))
    op.alter_column('procurement_plans', 'plan_name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=500),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('procurement_plans', 'plan_name',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.drop_column('procurement_plan_versions', 'is_executed')
    # ### end Alembic commands ###
