"""localization_level string

Revision ID: 70e2008117a2
Revises: cb6784e56428
Create Date: 2026-01-16 14:44:57.184374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70e2008117a2'
down_revision: Union[str, Sequence[str], None] = 'cb6784e56428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registry_data2')
    op.drop_table('registry_data2_2')
    op.alter_column('reestr_ktp', 'localization_level',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reestr_ktp', 'localization_level',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.create_table('registry_data2_2',
    sa.Column('product_code', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('registration_number', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bin_iin', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('company_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('oked_codes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('oked_names', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('region_kato', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('production_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('website', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('product_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('production_capacity', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tnved_code_10', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('kpved_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('kpved_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('enstru_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('enstru_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('agsk3_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('agsk3_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dvc_percent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('localization_level', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('registry_inclusion_date', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('registry_data2',
    sa.Column('product_code', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('registration_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bin_iin', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('company_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('oked_codes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('oked_names', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('region_kato', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('production_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('website', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('product_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('production_capacity', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tnved_code_10', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('kpved_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('kpved_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('enstru_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('enstru_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('agsk3_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('agsk3_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dvc_percent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('localization_level', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('registry_inclusion_date', sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
