"""delete is_resident

Revision ID: 7292178a746d
Revises: bdb9005e9310
Create Date: 2026-01-21 16:58:52.006893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7292178a746d'
down_revision: Union[str, Sequence[str], None] = 'bdb9005e9310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan_item_versions', 'is_resident')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan_item_versions', sa.Column('is_resident', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
