"""new version enstru

Revision ID: 757614209621
Revises: 70e2008117a2
Create Date: 2026-01-16 15:10:00.957628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '757614209621'
down_revision: Union[str, Sequence[str], None] = '70e2008117a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enstru', sa.Column('standard', sa.Text(), nullable=True))
    op.add_column('enstru', sa.Column('detail_rus', sa.Text(), nullable=True))
    op.add_column('enstru', sa.Column('type_name', sa.String(length=50), nullable=True))
    op.add_column('enstru', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('enstru', sa.Column('name_rus', sa.Text(), nullable=False))
    op.add_column('enstru', sa.Column('modify_datetime', sa.DateTime(), nullable=True))
    op.add_column('enstru', sa.Column('name_kaz', sa.Text(), nullable=False))
    op.add_column('enstru', sa.Column('type', sa.String(length=20), nullable=True))
    op.add_column('enstru', sa.Column('detail_eng', sa.Text(), nullable=True))
    op.add_column('enstru', sa.Column('uom', sa.String(length=50), nullable=True))
    op.add_column('enstru', sa.Column('name_eng', sa.Text(), nullable=True))
    op.add_column('enstru', sa.Column('detail_kaz', sa.Text(), nullable=True))
    op.add_column('enstru', sa.Column('create_datetime', sa.DateTime(), nullable=True))
    op.add_column('enstru', sa.Column('new_code', sa.String(length=35), nullable=True))
    op.add_column('enstru', sa.Column('purchasing_group_name', sa.Text(), nullable=True))
    op.add_column('enstru', sa.Column('purchasing_subgroup_name', sa.Text(), nullable=True))
    op.drop_column('enstru', 'name_ru')
    op.drop_column('enstru', 'specs_kz')
    op.drop_column('enstru', 'type_ru')
    op.drop_column('enstru', 'specs_ru')
    op.drop_column('enstru', 'name_kz')
    op.drop_column('enstru', 'type_kz')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enstru', sa.Column('type_kz', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('enstru', sa.Column('name_kz', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('enstru', sa.Column('specs_ru', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('enstru', sa.Column('type_ru', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('enstru', sa.Column('specs_kz', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('enstru', sa.Column('name_ru', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('enstru', 'purchasing_subgroup_name')
    op.drop_column('enstru', 'purchasing_group_name')
    op.drop_column('enstru', 'new_code')
    op.drop_column('enstru', 'create_datetime')
    op.drop_column('enstru', 'detail_kaz')
    op.drop_column('enstru', 'name_eng')
    op.drop_column('enstru', 'uom')
    op.drop_column('enstru', 'detail_eng')
    op.drop_column('enstru', 'type')
    op.drop_column('enstru', 'name_kaz')
    op.drop_column('enstru', 'modify_datetime')
    op.drop_column('enstru', 'name_rus')
    op.drop_column('enstru', 'is_active')
    op.drop_column('enstru', 'type_name')
    op.drop_column('enstru', 'detail_rus')
    op.drop_column('enstru', 'standard')
    # ### end Alembic commands ###
