"""add product_group table

Revision ID: 760428454ab7
Revises: 853d7f374043
Create Date: 2026-04-23 09:37:10.461115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '760428454ab7'
down_revision: Union[str, Sequence[str], None] = '853d7f374043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_groups', sa.Column('reestr_ktp_codes', sa.JSON(), nullable=True))
    op.drop_column('product_groups', 'product_word')
    op.drop_column('product_groups', 'product_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_groups', sa.Column('product_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('product_groups', sa.Column('product_word', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('product_groups', 'reestr_ktp_codes')
    # ### end Alembic commands ###
