"""add psd_document_item and agskenstruexclusive

Revision ID: 7be3647a66d9
Revises: 8812ce4ac0c7
Create Date: 2026-03-26 09:02:06.686263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7be3647a66d9'
down_revision: Union[str, Sequence[str], None] = '8812ce4ac0c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
