"""add vc procent works services

Revision ID: 7defd734427f
Revises: 9f8fd503ce3f
Create Date: 2026-01-27 10:55:29.449688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7defd734427f'
down_revision: Union[str, Sequence[str], None] = '9f8fd503ce3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем server_default='100' для заполнения существующих строк
    op.add_column('plan_item_versions', sa.Column('resident_share', sa.Numeric(precision=5, scale=2), nullable=False, server_default='100'))
    op.add_column('plan_item_versions', sa.Column('non_resident_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan_item_versions', 'non_resident_reason')
    op.drop_column('plan_item_versions', 'resident_share')
    # ### end Alembic commands ###
