"""add oked kpved tnved

Revision ID: 853d7f374043
Revises: bdf4c7309f19
Create Date: 2026-04-21 18:29:25.890784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '853d7f374043'
down_revision: Union[str, Sequence[str], None] = 'bdf4c7309f19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpved',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('name_kz', sa.String(length=1024), nullable=True),
    sa.Column('name_ru', sa.String(length=1024), nullable=True),
    sa.Column('parent_identificator', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oked',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('name_kz', sa.String(length=512), nullable=True),
    sa.Column('name_ru', sa.String(length=512), nullable=True),
    sa.Column('parent_identificator', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tnved',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('tree_name', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_last', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_keywords_keyword'), 'saved_keywords', ['keyword'], unique=True)
    op.create_table('keyword_pinned_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('ktp_item_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['keyword_id'], ['saved_keywords.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ktp_item_id'], ['reestr_ktp.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reestr_ktp_kpved_codes', 'reestr_ktp', ['kpved_codes'], unique=False, postgresql_using='gin')
    op.create_index('idx_reestr_ktp_oked_codes', 'reestr_ktp', ['oked_codes'], unique=False, postgresql_using='gin')
    op.create_index('idx_reestr_ktp_tnved_codes', 'reestr_ktp', ['tnved_codes'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_reestr_ktp_tnved_codes', table_name='reestr_ktp', postgresql_using='gin')
    op.drop_index('idx_reestr_ktp_oked_codes', table_name='reestr_ktp', postgresql_using='gin')
    op.drop_index('idx_reestr_ktp_kpved_codes', table_name='reestr_ktp', postgresql_using='gin')
    op.drop_table('keyword_pinned_items')
    op.drop_index(op.f('ix_saved_keywords_keyword'), table_name='saved_keywords')
    op.drop_table('saved_keywords')
    op.drop_table('tnved')
    op.drop_table('oked')
    op.drop_table('kpved')
    # ### end Alembic commands ###
