"""add agsk_enstru_exclusive table

Revision ID: 8812ce4ac0c7
Revises: 58596b0a8249
Create Date: 2026-03-26 03:25:32.786290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8812ce4ac0c7'
down_revision: Union[str, Sequence[str], None] = '58596b0a8249'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agsk_enstru_exclusive', 'agsk_code',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('agsk_enstru_exclusive', 'enstru_code',
               existing_type=sa.VARCHAR(length=35),
               nullable=False)
    op.alter_column('agsk_enstru_exclusive', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('agsk_enstru_exclusive_agsk_code_key', 'agsk_enstru_exclusive', type_='unique')
    op.drop_constraint('agsk_enstru_exclusive_enstru_code_key', 'agsk_enstru_exclusive', type_='unique')
    op.drop_index('idx_excl_score', table_name='agsk_enstru_exclusive')
    op.create_index('idx_excl_score', 'agsk_enstru_exclusive', ['score'], unique=False, postgresql_using='btree')
    op.create_index(op.f('ix_agsk_enstru_exclusive_agsk_code'), 'agsk_enstru_exclusive', ['agsk_code'], unique=True)
    op.create_index(op.f('ix_agsk_enstru_exclusive_enstru_code'), 'agsk_enstru_exclusive', ['enstru_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agsk_enstru_exclusive_enstru_code'), table_name='agsk_enstru_exclusive')
    op.drop_index(op.f('ix_agsk_enstru_exclusive_agsk_code'), table_name='agsk_enstru_exclusive')
    op.drop_index('idx_excl_score', table_name='agsk_enstru_exclusive', postgresql_using='btree')
    op.create_index('idx_excl_score', 'agsk_enstru_exclusive', [sa.text('score DESC')], unique=False)
    op.create_unique_constraint('agsk_enstru_exclusive_enstru_code_key', 'agsk_enstru_exclusive', ['enstru_code'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint('agsk_enstru_exclusive_agsk_code_key', 'agsk_enstru_exclusive', ['agsk_code'], postgresql_nulls_not_distinct=False)
    op.alter_column('agsk_enstru_exclusive', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agsk_enstru_exclusive', 'enstru_code',
               existing_type=sa.VARCHAR(length=35),
               nullable=True)
    op.alter_column('agsk_enstru_exclusive', 'agsk_code',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
