"""new versions15.04.2026

Revision ID: 9736ed141f55
Revises: 46cf5b5c9193
Create Date: 2026-04-15 15:24:25.576809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9736ed141f55'
down_revision: Union[str, Sequence[str], None] = '46cf5b5c9193'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_documents', sa.Column('sender_first_name', sa.String(length=100), nullable=True))
    op.add_column('external_documents', sa.Column('sender_last_name', sa.String(length=100), nullable=True))
    op.add_column('external_documents', sa.Column('sender_patronymic', sa.String(length=100), nullable=True))
    op.add_column('external_documents', sa.Column('sender_email', sa.String(length=255), nullable=True))
    op.add_column('external_documents', sa.Column('sender_phone', sa.String(length=50), nullable=True))
    op.add_column('external_documents', sa.Column('external_id', sa.String(length=100), nullable=True))
    op.add_column('external_documents', sa.Column('callback_url', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_external_documents_external_id'), 'external_documents', ['external_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_external_documents_external_id'), table_name='external_documents')
    op.drop_column('external_documents', 'callback_url')
    op.drop_column('external_documents', 'external_id')
    op.drop_column('external_documents', 'sender_phone')
    op.drop_column('external_documents', 'sender_email')
    op.drop_column('external_documents', 'sender_patronymic')
    op.drop_column('external_documents', 'sender_last_name')
    op.drop_column('external_documents', 'sender_first_name')
    # ### end Alembic commands ###
