"""Reestr_ktp recreate

Revision ID: 9a9036969042
Revises: 0a18404896d2
Create Date: 2026-01-06 09:29:03.360275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a9036969042'
down_revision: Union[str, Sequence[str], None] = '0a18404896d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reestr_ktp', sa.Column('product_code', sa.String(length=50), nullable=True))
    op.add_column('reestr_ktp', sa.Column('registration_number', sa.String(length=50), nullable=True))
    op.add_column('reestr_ktp', sa.Column('company_name', sa.String(length=500), nullable=False))
    op.add_column('reestr_ktp', sa.Column('oked_codes', sa.String(length=50), nullable=True))
    op.add_column('reestr_ktp', sa.Column('oked_names', sa.Text(), nullable=True))
    op.add_column('reestr_ktp', sa.Column('region_kato', sa.String(length=50), nullable=True))
    op.add_column('reestr_ktp', sa.Column('production_address', sa.Text(), nullable=True))
    op.add_column('reestr_ktp', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('reestr_ktp', sa.Column('phone', sa.String(length=100), nullable=True))
    op.add_column('reestr_ktp', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('reestr_ktp', sa.Column('product_name', sa.Text(), nullable=False))
    op.add_column('reestr_ktp', sa.Column('production_capacity', sa.String(length=255), nullable=True))
    op.add_column('reestr_ktp', sa.Column('tnved_code_10', sa.String(length=10), nullable=True))
    op.add_column('reestr_ktp', sa.Column('kpved_code', sa.String(length=20), nullable=True))
    op.add_column('reestr_ktp', sa.Column('kpved_name', sa.Text(), nullable=True))
    op.add_column('reestr_ktp', sa.Column('enstru_code', sa.String(length=50), nullable=True))
    op.add_column('reestr_ktp', sa.Column('enstru_name', sa.Text(), nullable=True))
    op.add_column('reestr_ktp', sa.Column('agsk3_code', sa.String(length=50), nullable=True))
    op.add_column('reestr_ktp', sa.Column('agsk3_name', sa.Text(), nullable=True))
    op.add_column('reestr_ktp', sa.Column('dvc_percent', sa.Float(), nullable=True))
    op.add_column('reestr_ktp', sa.Column('localization_level', sa.Integer(), nullable=True))
    op.add_column('reestr_ktp', sa.Column('registry_inclusion_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_reestr_ktp_bin_iin'), 'reestr_ktp', ['bin_iin'], unique=False)
    op.create_index(op.f('ix_reestr_ktp_id'), 'reestr_ktp', ['id'], unique=False)
    op.drop_column('reestr_ktp', 'full_name')
    op.drop_column('reestr_ktp', 'product_name_kz')
    op.drop_column('reestr_ktp', 'level_localization')
    op.drop_column('reestr_ktp', 'reg_number_application')
    op.drop_column('reestr_ktp', 'type_activity_oked')
    op.drop_column('reestr_ktp', 'actual_address')
    op.drop_column('reestr_ktp', 'kato_code')
    op.drop_column('reestr_ktp', 'tn_ved')
    op.drop_column('reestr_ktp', 'kpved')
    op.drop_column('reestr_ktp', 'product_name_ru')
    op.drop_column('reestr_ktp', 'date_add_reestr')
    op.drop_column('reestr_ktp', 'unit_per_year')
    op.drop_column('reestr_ktp', 'ens_tru_code')
    op.drop_column('reestr_ktp', 'agsk_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reestr_ktp', sa.Column('agsk_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('reestr_ktp', sa.Column('ens_tru_code', sa.VARCHAR(length=35), autoincrement=False, nullable=False))
    op.add_column('reestr_ktp', sa.Column('unit_per_year', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('reestr_ktp', sa.Column('date_add_reestr', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('reestr_ktp', sa.Column('product_name_ru', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('reestr_ktp', sa.Column('kpved', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('reestr_ktp', sa.Column('tn_ved', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('reestr_ktp', sa.Column('kato_code', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('reestr_ktp', sa.Column('actual_address', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('reestr_ktp', sa.Column('type_activity_oked', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('reestr_ktp', sa.Column('reg_number_application', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('reestr_ktp', sa.Column('level_localization', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('reestr_ktp', sa.Column('product_name_kz', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('reestr_ktp', sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_reestr_ktp_id'), table_name='reestr_ktp')
    op.drop_index(op.f('ix_reestr_ktp_bin_iin'), table_name='reestr_ktp')
    op.drop_column('reestr_ktp', 'registry_inclusion_date')
    op.drop_column('reestr_ktp', 'localization_level')
    op.drop_column('reestr_ktp', 'dvc_percent')
    op.drop_column('reestr_ktp', 'agsk3_name')
    op.drop_column('reestr_ktp', 'agsk3_code')
    op.drop_column('reestr_ktp', 'enstru_name')
    op.drop_column('reestr_ktp', 'enstru_code')
    op.drop_column('reestr_ktp', 'kpved_name')
    op.drop_column('reestr_ktp', 'kpved_code')
    op.drop_column('reestr_ktp', 'tnved_code_10')
    op.drop_column('reestr_ktp', 'production_capacity')
    op.drop_column('reestr_ktp', 'product_name')
    op.drop_column('reestr_ktp', 'email')
    op.drop_column('reestr_ktp', 'phone')
    op.drop_column('reestr_ktp', 'website')
    op.drop_column('reestr_ktp', 'production_address')
    op.drop_column('reestr_ktp', 'region_kato')
    op.drop_column('reestr_ktp', 'oked_names')
    op.drop_column('reestr_ktp', 'oked_codes')
    op.drop_column('reestr_ktp', 'company_name')
    op.drop_column('reestr_ktp', 'registration_number')
    op.drop_column('reestr_ktp', 'product_code')
    # ### end Alembic commands ###
