"""add_external_documents

Revision ID: 9bc6c0f58935
Revises: 4d9eeacabf2e
Create Date: 2026-02-20 10:55:00.936396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bc6c0f58935'
down_revision: Union[str, Sequence[str], None] = '4d9eeacabf2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=20), nullable=False),
    sa.Column('bank_name', sa.String(length=255), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('result_file_path', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('external_documents')
    # ### end Alembic commands ###
