"""new versiooon4

Revision ID: 9cd102a39d93
Revises: c362af09802e
Create Date: 2026-01-30 12:17:20.742269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cd102a39d93'
down_revision: Union[str, Sequence[str], None] = 'c362af09802e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan_item_executions', sa.Column('fact_vc_amount', sa.Numeric(precision=18, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan_item_executions', 'fact_vc_amount')
    # ### end Alembic commands ###
