"""updt

Revision ID: 9d1391e81a34
Revises: 0e3188729ab3
Create Date: 2026-05-12 04:55:53.833744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d1391e81a34'
down_revision: Union[str, Sequence[str], None] = '0e3188729ab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psd_document_items', sa.Column('item_type', sa.String(length=50), server_default='Товар', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('psd_document_items', 'item_type')
    # ### end Alembic commands ###
