"""add specs_kz

Revision ID: 9f8fd503ce3f
Revises: f89cdc4a64b6
Create Date: 2026-01-26 10:42:45.227833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f8fd503ce3f'
down_revision: Union[str, Sequence[str], None] = 'f89cdc4a64b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan_item_versions', sa.Column('additional_specs_kz', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan_item_versions', 'additional_specs_kz')
    # ### end Alembic commands ###
