"""new functional enstru_agsk

Revision ID: a4985fc1fc29
Revises: 5a02f5cbb6d6
Create Date: 2026-03-27 16:32:51.186084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a4985fc1fc29'
down_revision: Union[str, Sequence[str], None] = '5a02f5cbb6d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_excl_score', table_name='agsk_enstru_exclusive')
    op.add_column('agsk_enstru_manual_matches', sa.Column('ktp_id', sa.Integer(), nullable=True))
    op.add_column('agsk_enstru_manual_matches', sa.Column('product_name_ktp', sa.Text(), nullable=True))
    op.add_column('agsk_enstru_manual_matches', sa.Column('dvc_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    op.drop_constraint('uq_agsk_enstru_manual', 'agsk_enstru_manual_matches', type_='unique')
    op.create_unique_constraint('uq_agsk_enstru_ktp_manual', 'agsk_enstru_manual_matches', ['agsk_code', 'enstru_code', 'ktp_id'])
    op.drop_constraint('agsk_enstru_manual_matches_updated_by_fkey', 'agsk_enstru_manual_matches', type_='foreignkey')
    op.create_foreign_key(None, 'agsk_enstru_manual_matches', 'reestr_ktp', ['ktp_id'], ['id'])
    op.drop_column('agsk_enstru_manual_matches', 'agsk_full_name')
    op.drop_column('agsk_enstru_manual_matches', 'enstru_detail_ru')
    op.drop_column('agsk_enstru_manual_matches', 'reason')
    op.drop_column('agsk_enstru_manual_matches', 'score')
    op.drop_column('agsk_enstru_manual_matches', 'updated_by')
    op.drop_column('agsk_enstru_manual_matches', 'enstru_standard')
    op.drop_column('agsk_enstru_manual_matches', 'updated_at')
    op.drop_index('idx_psd_items_enstru', table_name='psd_document_items')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_psd_items_enstru', 'psd_document_items', ['enstru_code'], unique=False)
    op.add_column('agsk_enstru_manual_matches', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('agsk_enstru_manual_matches', sa.Column('enstru_standard', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('agsk_enstru_manual_matches', sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('agsk_enstru_manual_matches', sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('agsk_enstru_manual_matches', sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('agsk_enstru_manual_matches', sa.Column('enstru_detail_ru', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('agsk_enstru_manual_matches', sa.Column('agsk_full_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'agsk_enstru_manual_matches', type_='foreignkey')
    op.create_foreign_key('agsk_enstru_manual_matches_updated_by_fkey', 'agsk_enstru_manual_matches', 'users', ['updated_by'], ['id'])
    op.drop_constraint('uq_agsk_enstru_ktp_manual', 'agsk_enstru_manual_matches', type_='unique')
    op.create_unique_constraint('uq_agsk_enstru_manual', 'agsk_enstru_manual_matches', ['agsk_code', 'enstru_code'])
    op.drop_column('agsk_enstru_manual_matches', 'dvc_percent')
    op.drop_column('agsk_enstru_manual_matches', 'product_name_ktp')
    op.drop_column('agsk_enstru_manual_matches', 'ktp_id')
    op.create_index('idx_excl_score', 'agsk_enstru_exclusive', ['score'], unique=False)
    # ### end Alembic commands ###
