
"""Add revision_number to PlanItemVersion

Revision ID: a564a7fe9e75
Revises: f83d0ec3368c
Create Date: 2026-01-08 04:07:53.329679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a564a7fe9e75'
down_revision: Union[str, Sequence[str], None] = 'f83d0ec3368c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan_item_versions', sa.Column('revision_number', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan_item_versions', 'revision_number')
    # ### end Alembic commands ###
