"""init\

Revision ID: a78e435e386b
Revises: 
Create Date: 2025-11-26 17:20:02.931617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a78e435e386b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('need_type', sa.String(), nullable=False),
    sa.Column('enstru_code', sa.String(), nullable=True),
    sa.Column('enstru_name', sa.Text(), nullable=True),
    sa.Column('enstru_specs', sa.Text(), nullable=True),
    sa.Column('additional_specs', sa.Text(), nullable=True),
    sa.Column('agsk_3', sa.String(), nullable=True),
    sa.Column('expense_item', sa.String(), nullable=True),
    sa.Column('funding_source', sa.String(), nullable=True),
    sa.Column('kato_purchase', sa.String(), nullable=True),
    sa.Column('kato_delivery', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('marketing_price', sa.Float(), nullable=True),
    sa.Column('marketing_total', sa.Float(), nullable=True),
    sa.Column('planned_total_no_vat', sa.Float(), nullable=True),
    sa.Column('is_ktp', sa.Boolean(), nullable=True),
    sa.Column('ktp_applicable', sa.Boolean(), nullable=True),
    sa.Column('state', sa.Enum('DRAFT', 'SUBMITTED', 'PRE_APPROVED', 'BANK_DISCUSSED', 'FINAL_APPROVED', name='applicationstate'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
