"""Add VC metrics

Revision ID: a82a238fab15
Revises: 9a9036969042
Create Date: 2026-01-06 10:19:04.625104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a82a238fab15'
down_revision: Union[str, Sequence[str], None] = '9a9036969042'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan_item_versions', sa.Column('min_dvc_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('procurement_plan_versions', sa.Column('vc_mean', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('procurement_plan_versions', sa.Column('vc_median', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('procurement_plan_versions', sa.Column('vc_amount', sa.Numeric(precision=20, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('procurement_plan_versions', 'vc_amount')
    op.drop_column('procurement_plan_versions', 'vc_median')
    op.drop_column('procurement_plan_versions', 'vc_mean')
    op.drop_column('plan_item_versions', 'min_dvc_percent')
    # ### end Alembic commands ###
