"""new vers

Revision ID: af36c33fe5d8
Revises: a4985fc1fc29
Create Date: 2026-04-06 08:54:31.369007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af36c33fe5d8'
down_revision: Union[str, Sequence[str], None] = 'a4985fc1fc29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_agsk_enstru_exclusive_agsk_code', table_name='agsk_enstru_exclusive')
    op.drop_index('ix_agsk_enstru_exclusive_enstru_code', table_name='agsk_enstru_exclusive')
    op.drop_table('agsk_enstru_exclusive')
    op.drop_index('ix_agsk_enstru_manual_matches_agsk_code', table_name='agsk_enstru_manual_matches')
    op.drop_index('ix_agsk_enstru_manual_matches_enstru_code', table_name='agsk_enstru_manual_matches')
    op.drop_table('agsk_enstru_manual_matches')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agsk_enstru_manual_matches',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('agsk_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('enstru_code', sa.VARCHAR(length=35), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('agsk_name_ru', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('enstru_name_ru', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('psd_document_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ktp_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_name_ktp', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dvc_percent', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='agsk_enstru_manual_matches_created_by_fkey'),
    sa.ForeignKeyConstraint(['enstru_code'], ['enstru.code'], name='agsk_enstru_manual_matches_enstru_code_fkey'),
    sa.ForeignKeyConstraint(['ktp_id'], ['reestr_ktp.id'], name='agsk_enstru_manual_matches_ktp_id_fkey'),
    sa.ForeignKeyConstraint(['psd_document_id'], ['external_documents.id'], name='agsk_enstru_manual_matches_psd_document_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='agsk_enstru_manual_matches_pkey'),
    sa.UniqueConstraint('agsk_code', 'enstru_code', 'ktp_id', name='uq_agsk_enstru_ktp_manual')
    )
    op.create_index('ix_agsk_enstru_manual_matches_enstru_code', 'agsk_enstru_manual_matches', ['enstru_code'], unique=False)
    op.create_index('ix_agsk_enstru_manual_matches_agsk_code', 'agsk_enstru_manual_matches', ['agsk_code'], unique=False)
    op.create_table('agsk_enstru_exclusive',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('agsk_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('enstru_code', sa.VARCHAR(length=35), autoincrement=False, nullable=False),
    sa.Column('name_ru_agsk', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('agsk_full_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name_ru_enstru', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('detail_enstru', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('standard_enstru', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='agsk_enstru_exclusive_pkey')
    )
    op.create_index('ix_agsk_enstru_exclusive_enstru_code', 'agsk_enstru_exclusive', ['enstru_code'], unique=True)
    op.create_index('ix_agsk_enstru_exclusive_agsk_code', 'agsk_enstru_exclusive', ['agsk_code'], unique=True)
    # ### end Alembic commands ###
