"""new version enstru2

Revision ID: bdb9005e9310
Revises: 757614209621
Create Date: 2026-01-16 15:34:47.836139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdb9005e9310'
down_revision: Union[str, Sequence[str], None] = '757614209621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('enstru', 'name_rus',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('enstru', 'name_kaz',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('enstru', 'name_kaz',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('enstru', 'name_rus',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
