"""new versions20.04.2026

Revision ID: bdf4c7309f19
Revises: 3a62c46dadb2
Create Date: 2026-04-20 16:11:06.577026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdf4c7309f19'
down_revision: Union[str, Sequence[str], None] = '3a62c46dadb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_documents', sa.Column('director_comment', sa.Text(), nullable=True))
    op.add_column('external_documents', sa.Column('deadline_days', sa.Integer(), nullable=True))
    op.add_column('external_documents', sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('external_documents', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.add_column('users', sa.Column('delegated_to_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('delegation_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('delegation_end', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['delegated_to_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'delegation_end')
    op.drop_column('users', 'delegation_start')
    op.drop_column('users', 'delegated_to_id')
    op.alter_column('external_documents', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_column('external_documents', 'deadline_at')
    op.drop_column('external_documents', 'deadline_days')
    op.drop_column('external_documents', 'director_comment')
    # ### end Alembic commands ###
