"""Add executed_quantity to PlanItemVersion

Revision ID: c145b43dde34
Revises: 6082afeeb7f8
Create Date: 2025-12-31 12:21:11.014131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c145b43dde34'
down_revision: Union[str, Sequence[str], None] = '6082afeeb7f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan_item_versions', sa.Column('executed_quantity', sa.Numeric(precision=12, scale=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan_item_versions', 'executed_quantity')
    # ### end Alembic commands ###
