"""new versiooon

Revision ID: c362af09802e
Revises: 0f85a22ac939
Create Date: 2026-01-30 10:06:32.994492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c362af09802e'
down_revision: Union[str, Sequence[str], None] = '0f85a22ac939'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan_item_versions', sa.Column('executed_vc_amount', sa.Numeric(precision=18, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan_item_versions', 'executed_vc_amount')
    # ### end Alembic commands ###
