"""Add vc_amount to PlanItemVersion

Revision ID: cb6784e56428
Revises: 0a82f9e0fa8a
Create Date: 2026-01-16 09:34:19.619311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb6784e56428'
down_revision: Union[str, Sequence[str], None] = '0a82f9e0fa8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan_item_versions', sa.Column('vc_amount', sa.Numeric(precision=18, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan_item_versions', 'vc_amount')
    # ### end Alembic commands ###
