"""new versiooon6

Revision ID: ce0ca072ee48
Revises: 92a9068c79ad
Create Date: 2026-02-04 17:05:06.177726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce0ca072ee48'
down_revision: Union[str, Sequence[str], None] = '92a9068c79ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan_item_versions', sa.Column('original_unit_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan_item_versions', 'original_unit_name')
    # ### end Alembic commands ###
