"""removeenstrufrompsditems

Revision ID: ee71551c0db6
Revises: 1db0735cc7fc
Create Date: 2026-04-29 16:32:20.671537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee71551c0db6'
down_revision: Union[str, Sequence[str], None] = '1db0735cc7fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('psd_document_items_enstru_code_fkey', 'psd_document_items', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('psd_document_items_enstru_code_fkey', 'psd_document_items', 'enstru', ['enstru_code'], ['code'])
    # ### end Alembic commands ###
