"""add_completed_at

Revision ID: eeefdd934411
Revises: 977da3e8eefc
Create Date: 2026-02-23 10:52:42.247073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeefdd934411'
down_revision: Union[str, Sequence[str], None] = '977da3e8eefc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_documents', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('external_documents', 'completed_at')
    # ### end Alembic commands ###
