"""add analyst comment

Revision ID: f2065a160a9a
Revises: 760428454ab7
Create Date: 2026-04-28 15:32:21.504109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2065a160a9a'
down_revision: Union[str, Sequence[str], None] = '760428454ab7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_documents', sa.Column('analyst_comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('external_documents', 'analyst_comment')
    # ### end Alembic commands ###
