"""Add root_item relationship

Revision ID: f83d0ec3368c
Revises: a82a238fab15
Create Date: 2026-01-08 03:53:40.674569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f83d0ec3368c'
down_revision: Union[str, Sequence[str], None] = 'a82a238fab15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'plan_item_versions', 'plan_item_versions', ['root_item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plan_item_versions', type_='foreignkey')
    # ### end Alembic commands ###
