"""numeric goods services

Revision ID: f89cdc4a64b6
Revises: 7292178a746d
Create Date: 2026-01-22 09:52:03.906446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f89cdc4a64b6'
down_revision: Union[str, Sequence[str], None] = '7292178a746d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_version_item', 'plan_item_versions', type_='unique')
    op.create_unique_constraint('uq_version_item_type', 'plan_item_versions', ['version_id', 'item_number', 'need_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_version_item_type', 'plan_item_versions', type_='unique')
    op.create_unique_constraint('uq_version_item', 'plan_item_versions', ['version_id', 'item_number'])
    # ### end Alembic commands ###
